version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     ports:
       - "3306:3306"
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} 
       - MYSQL_DATABASE=${MYSQL_DATABASE} 
       - MYSQL_USER=${MYSQL_USER} 
       - MYSQL_PASSWORD=${MYSQL_PASSWORD} 

   wordpress:
     depends_on:
       - db
     image: wordpress_with_xsl
     volumes:
       - ./wp:/var/www/html
     ports:
       - "8000:80"
     restart: always
     environment:
       - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
       - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
       - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
       - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
       - WORDPRESS_DEBUG=${WORDPRESS_DEBUG}
volumes:
    db_data: {}



